apiVersion: v1
kind: Pod
metadata:
  name: react-portfolio-pod
  labels:
    app: react-portfolio
spec:
  containers:
    - name: react-portfolio-container
      image: aditya280102/my-portfolio:latest
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
