apiVersion: v1
kind: Service
metadata:
  name: react-portfolio-service
  labels:
    app: react-portfolio
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: react-portfolio
