apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-portfolio
    app.kubernetes.io/instance: gitops-with-argocd
  name: react-portfolio-service
  namespace: argocd
spec:
  ports:
    - nodePort: 32001          # Changed NodePort to 32001
      port: 3000
      targetPort: 3000
  selector:
    app: react-portfolio
  type: NodePort
